#!/bin/bash
#------------------------------------------------------------------------------------------#
# Script to extract motion from the OF log.overInterDyMFoam file 
# Usage: ./extractMotion.sh OF_case_directory
# Output: Motion.txt will be placed inside the specified OF_case_directory
# Note: the provided plotMotion.py can be used to visualize the results.
#------------------------------------------------------------------------------------------#
## Check if OF log file exists
if [ -z "$1" ]; then
    echo $'\nMissing case input for extracting data!'
    echo $'\nUsage: \n \t ./extractMotion.sh OF_case_directory\n'
    exit 1
else
    echo -e '\nExtracting data for:'
fi

## Extracting data from log file
for dir in "$@"
do
    echo -e "\t$dir"

    # Get case settings
    nOuterCorrectors=$(cat $dir/system/fvSolution | grep 'nOuterCorrectors' | awk '{print $2}' | tr -d ';')
    getNthLines='sed -n 1~'$nOuterCorrectors'p'
    trim='tr -d "()"'

    file=$dir/log.overInterDyMFoam
    fileOut=$dir/Motion.txt

    if [ ! -f $file ]; then
        echo "log.overInterDyMFoam file not found in $dir!"
        exit 1
    fi

    if [ -f $fileOut ];then
        rm $fileOut
    fi

    touch $fileOut

    # Time
    cat $file | grep "Time = " | sed -n '1~2p' | cut --complement -c1-7 >> Time

    # Center of mass
    cat $file | grep "Centre of mass:" | $trim | $getNthLines | cut --complement -c1-20 >> Xt

    # Rotational matrix
    cat $file | grep "Orientation:" | $trim | $getNthLines | cut --complement -c1-17 >> Xr

    # Linear velocity
    cat $file | grep "Linear velocity:" | $trim | $getNthLines | cut --complement -c1-20 >> Xdt

    # Angular velocity
    cat $file | grep "Angular velocity:" | $trim | $getNthLines | cut --complement -c1-22 >> Xdr

    # Create header
    echo '*************************Generated by extractMotion.sh**********************' >> header
    echo -e "*      $(date) - Case: $dir"                                               >> header
    echo '* Note: Data was extracted from log.overInterDyMFoam using extractMotion.sh'  >> header
    echo '*       Can be visualized with plotMotion.py                            '     >> header
    echo '****************************************************************************' >> header
    echo "Time X(x3) Orientation(x9) dX(x3) dX_angular(x3)"                             >> header

    # Create output file
    paste -d' ' Time Xt Xr Xdt Xdr >> output

    cat header output >> $fileOut

    rm header Time Xt Xr Xdt Xdr output
done

echo -e 'Completed!\n'
