#!/usr/bin/env python3
##--------------------------------------------------------------------------------#
# Script to plot total forces on WEC from Forces.txt file generated by extractForces.sh
# Usage: python plotForces.py OF_case_directory (single or multiple cases)
##--------------------------------------------------------------------------------#
import sys
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#---------------------------------Plot settings-----------------------------#
#plt.rcParams['figure.dpi'] = 400
colors = np.array(
['#4477AA', # blue
  '#66CCEE', # cyan
  '#228833', # green
  '#CCBB44', # yellow
  '#EE6677', # red
  '#AA3377', # purple
  '#BBBBBB'] # grey]
)

# colormap from: https://personal.sron.nl/~pault/
plt.rcParams['axes.prop_cycle'] = plt.cycler(color=colors)

##--------------------------------------------------------------------------------#
# Read input data file
def readData(filename):
    ufData = pd.read_csv(filename, sep="\s+|\t,", header=None, skiprows=6,
                                    names = range(100), engine="python")

    time = ufData[0]
    Fx = ufData[1]
    Fy = ufData[2]
    Fz = ufData[3]

    return time, Fx, Fy, Fz
##--------------------------------------------------------------------------------#
# Read inputs
nCases = len(sys.argv)-1
if (nCases < 1):
    print('\nMissing case input(s) for plotting!')
    print('\nUsage: \n \t python plotForces.py OF_case_directories\n')
    sys.exit(1)

# Plotting outputs
fig, axs = plt.subplots(3,1,figsize=(8,4), tight_layout=True)
for case in sys.argv[1:]:
    time, Fx, Fy, Fz = readData(os.path.join(case,"Forces.txt"))

    axs[0].plot(time, Fx, label=case)
    axs[1].plot(time, Fy, label=case)
    axs[2].plot(time, Fz, label=case)

yLabels = ['Fx (N)','Fy (N)','Fz (N)']
for i in range(3):
    axs[i].legend()
    axs[i].set_ylabel(yLabels[i])

axs[-1].set_xlabel('Time (s)')

plt.legend()
plt.show()
