#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Source the tutorial run functions for use here
#------------------------------------------------------------------------------

cleanCase0

#------------------------------------------------------------------------------
