#!/bin/bash
#------------------------------------------------------------------------------------------#
# Script to extract motion and forces from the OF log.overInterDyMFoam file 
# Usage: ./extractLog.sh OF_case_directory
# Output: Output.txt will be placed inside the specified OF_case_directory
# Note: the provided plotMotion.py and plotForces.py can be used to visualize the results.
#------------------------------------------------------------------------------------------#
trim='tr -d "()"'
getNthLines='sed -n 1~3p'

if [ -z "$1" ]; then
    echo $'\nMissing case input for extracting data!'
    echo $'\nUsage: \n \t ./extractLog.sh OF_case_directory\n'
    exit 1
fi

for dir in "$@"
do
    file=$dir/log.overInterDyMFoam
    fileOut=$dir/Output.txt

    if [ ! -f $file ]; then
        echo "log.overInterDyMFoam file not found in $dir!"
        exit 1
    fi

    if [ -f $fileOut ];then
        rm $fileOut
    fi

    touch $fileOut

    # Time
    cat $file | grep "Time = " | sed -n '1~2p' | cut --complement -c1-7 >> Time

    # Center of mass
    cat $file | grep "Centre of mass:" | $trim | $getNthLines | cut --complement -c1-20 >> Xt

    # Rotational matrix
    cat $file | grep "Orientation:" | $trim | $getNthLines | cut --complement -c1-17 >> Xr

    # Linear velocity
    cat $file | grep "Linear velocity:" | $trim | $getNthLines | cut --complement -c1-20 >> Xdt

    # Angular velocity
    cat $file | grep "Angular velocity:" | $trim | $getNthLines | cut --complement -c1-22 >> Xdr

    # Total body force
    cat $file | grep "Total    : " | tr -d "():Total" | sed -n 1~2p >> Fnet

    # Total body moment
    cat $file | grep "Total    : " | tr -d "():Total" | sed -n 2~2p >> Mnet

    # Create header
    echo '*************************Generated by extractLog.sh*************************' >> header
    echo -e "*      $(date). Case: $dir"                                                >> header
    echo '* Note: Data was extracted from log.overInterDyMFoam using extractLog.sh'     >> header
    echo '*       Can be visualized with plotMotion.py and/or plotForces.py'            >> header
    echo '****************************************************************************' >> header
    echo "Time X(x3) Orientation(x9) dX(x3) dX_angular(x3) Force(x3) Moment(x3)"        >> Params

    # Create output file
    paste -d' ' Time Xt Xr Xdt Xdr Fnet Mnet >> output

    cat header Params output >> $fileOut

    rm header Params Time Xt Xr Xdt Xdr Fnet Mnet output
done
