#!/bin/bash
#------------------------------------------------------------------------------------------#
# Script to extract forces and moments from the OF log.overInterDyMFoam file 
# Usage: ./extractForces.sh OF_case_directory
# Output: Forces.txt will be placed inside the specified OF_case_directory
# Note: the provided plotForces.py can be used to visualize the results.
#------------------------------------------------------------------------------------------#
## Number of expected forcing objects
nForces=1

## Check if OF log file exists
if [ -z "$1" ]; then
    echo $'\nMissing case input for extracting data!'
    echo $'\nUsage: \n \t ./extractForces.sh OF_case_directory\n'
    exit 1
else
    echo -e '\nExtracting data for:'
fi

## Extracting data from log file
for dir in "$@"
do
    echo -e "\t$dir"

    # Get case settings
    file=$dir/log.overInterDyMFoam
    fileOut=$dir/Forces.txt

    if [ ! -f $file ]; then
        echo "log.overInterDyMFoam file not found in $dir!"
        exit 1
    fi

    if [ -f $fileOut ];then
        rm $fileOut
    fi

    touch $fileOut

    # Time
    cat $file | grep "Time = " | sed -n '1~2p' | cut --complement -c1-7 >> Time

    # Total body force
    cat $file | grep "Total    : " | tr -d "():Total" | sed -n 1~$(($nForces*2))p >> Fnet

    # Total body moment
    cat $file | grep "Total    : " | tr -d "():Total" | sed -n 2~$(($nForces*2))p >> Mnet

    # Create header
    echo '*************************Generated by extractForces.sh*************************' >> header
    echo -e "*      $(date) - Case: $dir"                                                  >> header
    echo '* Note: Data was extracted from log.overInterDyMFoam using extractForces.sh'     >> header
    echo '*       Can be visualized with plotForces.py'                                    >> header
    echo '*******************************************************************************' >> header
    echo "Time X(x3) Force(x3) Moment(x3)"                                                 >> header

    # Create output file
    paste -d' ' Time Fnet Mnet >> output

    cat header output >> $fileOut

    rm header Time Fnet Mnet output
done

echo -e 'Completed!\n'
