#!/bin/bash
#------------------------------------------------------------------------------------------#
# Script to extract restraint forces from the OF log.overInterDyMFoam file
# Usage: ./extractTensions.sh OF_case_directory
# Output: Tensions.txt will be placed inside the specified OF_case_directory
# Note: the provided plotTensions.py can be used to visualize the results.
#------------------------------------------------------------------------------------------#
## User input
nLines=3

if [ -z "$1" ]; then
    echo $'\nMissing case input for extracting data!'
    echo $'\nUsage: \n \t ./extractRestraint.sh OF_case_directory\n'
    exit 1
else
    echo -e '\nExtracting data for:'
fi

for dir in "$@"
do
    echo -e "\t$dir"

    # Get case settings
    nOuterCorrectors=$(cat $dir/system/fvSolution | grep 'nOuterCorrectors' | awk '{print $2}' | tr -d ';')
    nSkips=$(($nLines*$nOuterCorrectors))
    trim='tr -d "()"'

    file=$dir/log.overInterDyMFoam
    if [ ! -f $file ]; then
        echo "log.overInterDyMFoam file not found in $dir!"
        exit 1
    fi

    fileOut=$dir'/Tensions.txt'
    if [ -f $fileOut ];then
        rm $fileOut
    fi
    touch $fileOut

    for i in $(seq 1 $nLines)
    do
        cat $fileOut > fTemp
        cat $file | grep "Restraint" | $trim | sed -n $i~$nSkips'p' | awk '{print $(NF-2),"\t",$(NF-1),"\t",$(NF)}' > tTemp
        paste -d"\t" fTemp tTemp > $fileOut

        if [ $i == 1 ]; then
            echo "Time Line1_fx Line1_fy Line1_fz"        > Params
        else
            echo 'Line'$i'_fx' 'Line'$i'_fy' 'Line'$i'_fz' > pTemp
            cat Params > parTemp
            paste -d"\t" parTemp pTemp > Params
        fi
    done 

    # Time
    cat $file | grep "Time = " | sed -n '1~2p' | cut --complement -c1-7 >> Time

    # Create header
    echo '*************************Generated by extractTensions.sh************************' >> header
    echo -e "*      $(date) - Case: $dir"                                                   >> header
    echo '* Note: Data was extracted from log.overInterDyMFoam using extractTensions.sh'    >> header
    echo '*       Can be visualized with plotTensions.py'                                   >> header
    echo '********************************************************************************' >> header

    # Combine tensions with time
    cat $fileOut > fTemp
    paste -d"\t" Time fTemp > $fileOut

    # Add header to file
    cat $fileOut > fTemp
    cat header Params fTemp > $fileOut

    rm tTemp fTemp pTemp parTemp Time Params header
done

echo -e 'Completed!\n'
