#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

# Clean residue files
files=("objBoundingBox" "objMeshing")

for file in "${files[@]}"
do
    if [ -f 'constant/'$file ]; then
        rm 'constant/'$file
    fi
done

if [ "$(ls -A constant/extendedFeatureEdgeMesh/)" ]; then
    rm constant/extendedFeatureEdgeMesh/*
fi

if [ "$(ls -A constant/triSurface/)" ]; then
    rm constant/triSurface/*
fi

#------------------------------------------------------------------------------

