#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------#

# Set up the simulation folder
if [ -f log.interFoam ]
then
  ./restart.sh
else
  # Clean the run directory
  ./Allclean
  restore0Dir

  # Create the flume's simulation grid
  runApplication blockMesh
  if [ $? -ne 0 ]; then
    exit 1
  fi

  # Decompose the case for parallel run
  runApplication decomposePar
  if [ $? -ne 0 ]; then
    exit 1
  fi

  # Run setFields
  runParallel setFields
  if [ $? -ne 0 ]; then
    exit 1
  fi
fi

# Start the simulation
runParallel $(getApplication)
if [ $? -ne 0 ]; then
  exit 1
fi


#runApplication reconstructPar

#runApplication foamToVTK

#------------------------------------------------------------------------------#
